services:
    db:
        image: postgres:18.0
        environment:
            - POSTGRES_DB=smarthome_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
        volumes:
            - ./shdb:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - "8883:8883"
        volumes:
            - ./mosquitto/config:/mosquitto/config:ro
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
            - ./certs:/mosquitto/config/certs

    api:
        build:
            context: ./backend
            dockerfile: Containerfile
        env_file:
            - .env.prod
        volumes:
            - ./certs:/app/certs:ro
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
            mosquitto:
                condition: service_started
        restart: always

    mqtt-bridge:
        build:
            context: ./backend
            dockerfile: Containerfile
        command: uv run python -u manage.py run_mqtt_bridge
        env_file:
            - .env.prod
        environment:
            - MQTT_CLIENT_ID=mqtt-bridge
        volumes:
            - ./certs:/app/certs:ro
        depends_on:
            - db
            - mosquitto
        restart: always

    heartbeat-monitor:
        build:
            context: ./backend
            dockerfile: Containerfile
        command: uv run python -u manage.py run_heartbeat_monitor --interval 10 --threshold 20
        env_file:
            - .env.prod
        volumes:
            - ./certs:/app/certs:ro
        depends_on:
            - db
            - mosquitto
        restart: always

    gateway:
        build:
            context: ./simulations
            dockerfile: Containerfile
        volumes:
            - ./certs:/app/certs:ro
        env_file:
            - .env.prod

    frontend:
        build:
            context: ./frontend
            dockerfile: Containerfile
        env_file:
            - .env.prod
        environment:
            - ORIGIN=http://localhost:3000
        ports:
            - "3000:3000"

volumes:
    smart_home_postgres_volume:
