# Generated by Django 6.0.4 on 2026-05-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_deviceaction_options_alter_sensordata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='devices.home')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.room'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['home', 'room'], name='devices_dev_home_id_f93b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['home', 'name'], name='devices_roo_home_id_f2c8d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('home', 'name'), name='unique_room_per_home'),
        ),
    ]
