# Generated by Django 6.0.4 on 2026-06-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_room_device_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.home'),
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('hardware_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_fingerprint', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways', to='devices.home')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.gateway'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['gateway'], name='devices_dev_gateway_39cd8b_idx'),
        ),
    ]
