# Generated by Django 6.0.4 on 2026-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_home_gateway_device_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='pairing_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
