# Generated by Django 6.0.4 on 2026-05-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='homeinvite',
            new_name='invites_hom_home_id_ad9a7a_idx',
            old_name='inv_home_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='homeinvite',
            new_name='invites_hom_home_id_0611c5_idx',
            old_name='inv_home_used_idx',
        ),
        migrations.RenameIndex(
            model_name='homeinvite',
            new_name='invites_hom_home_id_1efb7c_idx',
            old_name='inv_home_rev_idx',
        ),
    ]
